{
  "summary": {
    "total_tasks": 5,
    "successful_runs": 5,
    "passed_evaluations": 1,
    "success_rate": "20.00%",
    "total_execution_time": "293.81 seconds",
    "total_agent_cost": 0.0282,
    "total_user_cost": 0.0946,
    "failure_reasons": {
      "fail_to_pass_log_check": 3,
      "fail_to_pass_local_state_check": 1
    }
  },
  "failed_tasks": [
    {
      "task_id": "dev_filesystem_002",
      "task_path": "tasks/dev/filesystem_002.json",
      "failure": "fail_to_pass_log_check",
      "details": "Failed in executing the command: Traceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/weka-jd/prod/containers/lijunlong/dev/codes/mcpbench_dev/groundtruth/dev/filesystem_002/check_log.py\", line 47, in <module>\n    raise RuntimeError(f\"Fail to find all needed outputs in the log!\\n{error_msg}\".strip())\nRuntimeError: Fail to find all needed outputs in the log!\n`food_total` = 530 not found!\n`all_total` = 675.4 not found!\n"
    },
    {
      "task_id": "dev_filesystem_005",
      "task_path": "tasks/dev/filesystem_005.json",
      "failure": "fail_to_pass_log_check",
      "details": "Failed in executing the command: Traceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/weka-jd/prod/containers/lijunlong/dev/codes/mcpbench_dev/groundtruth/dev/filesystem_005/check_log.py\", line 47, in <module>\n    raise RuntimeError(f\"Fail to find all needed outputs in the log!\\n{error_msg}\".strip())\nRuntimeError: Fail to find all needed outputs in the log!\n`food_total` = 530 not found!\n`traffic_total` = 54.4 not found!\n`others_total` = 91 not found!\n`all_total` = 675.4 not found!\n"
    },
    {
      "task_id": "dev_filesystem_003",
      "task_path": "tasks/dev/filesystem_003.json",
      "failure": "fail_to_pass_local_state_check",
      "details": "Failed in executing the command: Traceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/weka-jd/prod/containers/lijunlong/dev/codes/mcpbench_dev/groundtruth/dev/filesystem_003/check_local.py\", line 19, in <module>\n    assert agent_generated_data[date][category] == value\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAssertionError\n"
    },
    {
      "task_id": "dev_filesystem_001",
      "task_path": "tasks/dev/filesystem_001.json",
      "failure": "fail_to_pass_log_check",
      "details": "Failed in executing the command: Traceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/weka-jd/prod/containers/lijunlong/dev/codes/mcpbench_dev/groundtruth/dev/filesystem_001/check_log.py\", line 47, in <module>\n    raise RuntimeError(f\"Fail to find all needed outputs in the log!\\n{error_msg}\".strip())\nRuntimeError: Fail to find all needed outputs in the log!\n`food_total` = 530 not found!\n`all_total` = 675.4 not found!\n"
    }
  ],
  "execution_info": {
    "start_time": "2025-05-30T19:22:50.757119",
    "end_time": "2025-05-30T19:24:21.424752",
    "total_batch_time": 90.667633,
    "max_concurrent": 10
  }
}